[project]
name = "htx-takehome"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "accelerate==0.33.0",
    "datasets==2.20.0",
    "pandas==2.2.2",
    "scikit-learn==1.5.1",
    "transformers==4.44.0",
    "torch==2.3.1",
    "ipykernel>=7.2.0",
    "pytest>=9.0.3",
]

[tool.uv.sources]
torch = { index = "pytorch-cu121" }

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true
